---
- name: Installer et configurer docker
  hosts: tp4
  remote_user: vagrant
  become: true
  become_user: root

  vars:
    docker_users:
      - vagrant

  roles:
    - geerlingguy.docker
    - geerlingguy.clamav
